### PR TITLE
Release `0.1.7`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `0.1.7` release.
Here you can find all related translations changes: [0.1.6...master](https://github.com/flarum-lang/hindi/compare/0.1.6...master).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## 0.1.7

**सामान्य अद्यतन**:

* Day.js अनुवाद अपडेट किये गए हैं.
* Flarum कोर अनुवाद अपडेट किये गए हैं.

**नए एक्सटेंशन के लिए समर्थन जोड़ा गया है**:

* [`acpl/flarum-lscache`](https://github.com/android-com-pl/flarum-lscache)
* [`antoinefr/flarum-ext-money`](https://github.com/AntoineFr/flarum-ext-money)
* [`flarum/akismet`](https://github.com/flarum/akismet)
* [`flarum/approval`](https://github.com/flarum/approval)
* [`flarum/bbcode`](https://github.com/flarum/bbcode)
* [`flarum/emoji`](https://github.com/flarum/emoji)
* [`flarum/flags`](https://github.com/flarum/flags)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/lock`](https://github.com/flarum/lock)
* [`flarum/markdown`](https://github.com/flarum/markdown)
* [`flarum/suspend`](https://github.com/flarum/suspend)
* [`flarum/tags`](https://github.com/flarum/tags)

सभी परिवर्तन: [0.1.6...0.1.7](https://github.com/flarum-lang/hindi/compare/0.1.6...0.1.7)।

</details>

### CODE REVIEW

**Comment by rob006** [comment]
@Hari-Bonda @meetdilip Just as a note, this is an automated PR generated by bot. The idea is to simplify release process for language pack maintainers - all you need is to approve this pull request and bot will handle the rest. You can read more about the process at forum: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76 . If you don't want to use this feature, let me know.

**Comment by rob006** [comment]
BTW: @Hari-Bonda it looks like you don't have maintainer permission of Weblate. Do you want it?

**Comment by Hari-Bonda** [comment]
> BTW: @Hari-Bonda it looks like you don't have maintainer permission of Weblate. Do you want it?

I have gone through the changes, everything looks okay to me. you can merge.

For now, i don't want to maintain this.

**Comment by rob006** [comment]
@Hari-Bonda I removed you from maintainers of this repository, so you should not be automatically assigned to future release PRs.

@meetdilip Do you want to maintain this language pack? If you don't have time for this, I'll adjust description of this repo and Weblate config to better fit situation where there is no maintainer.

**Comment by rob006** [comment]
@meetdilip It's been over 2 months with no response from you. It is important to tag new releases when new transliterations appear, because by default composer installs only stable versions of packages. It means that all translations added after last release are inaccessible for most of the users. In case of no response from you, I'm going to mark this language pack as unmaintained, so its state will be more clear for users. It means that:
* I'll add info in readme that this language pack is searching for maintainer.
* Command for installing package will use `dev-master` as version, so users will benefit from translations not included in last stable release.
* All translations on Weblate will be marked as unverified, so community will be able to edit them without any restrictions.
* You will keep permissions on Weblate and this repository, but if anyone will volunteer to maintain this language pack, he will replace you as maintainer.

**Comment by rob006** [comment]
> In case of no response from you, I'm going to mark this language pack as unmaintained, so its state will be more clear for users. It means that:
>  * I'll add info in readme that this language pack is searching for maintainer.
>  * Command for installing package will use `dev-master` as version, so users will benefit from translations not included in last stable release.
>  * All translations on Weblate will be marked as unverified, so community will be able to edit them without any restrictions.
>  * You will keep permissions on Weblate and this repository, but if anyone will volunteer to maintain this language pack, he will replace you as maintainer.

Done.

**Comment by ItsNeil17** [comment]
flarum-markdown extension has been fully translated into Hindi, changes committed to be seen within the next hour.

**Review by ItsNeil17 — APPROVED** [review]
flarum/core has been fully translated along with a few other extensions.

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## संस्करण [`0.1.7`](https://github.com/flarum-lang/hindi/releases/tag/0.1.7)

**सामान्य अद्यतन**:

* Day.js अनुवाद अपडेट किये गए हैं.
* Flarum कोर अनुवाद अपडेट किये गए हैं.


**नए एक्सटेंशन के लिए समर्थन जोड़ा गया है**:

* [`acpl/flarum-lscache`](https://github.com/android-com-pl/flarum-lscache)
* [`antoinefr/flarum-ext-money`](https://github.com/AntoineFr/flarum-ext-money)
* [`flarum/akismet`](https://github.com/flarum/akismet)
* [`flarum/approval`](https://github.com/flarum/approval)
* [`flarum/bbcode`](https://github.com/flarum/bbcode)
* [`flarum/emoji`](https://github.com/flarum/emoji)
* [`flarum/flags`](https://github.com/flarum/flags)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/lock`](https://github.com/flarum/lock)
* [`flarum/markdown`](https://github.com/flarum/markdown)
* [`flarum/suspend`](https://github.com/flarum/suspend)
* [`flarum/tags`](https://github.com/flarum/tags)


सभी परिवर्तन: [0.1.6...0.1.7](https://github.com/flarum-lang/hindi/compare/0.1.6...0.1.7)।

अपडेट करने के लिए इन आदेशों को चलाएँ:

```console
composer update flarum-lang/hindi
php flarum cache:clear
```

~~~

**Pull request merged**
