### PR TITLE
Release `0.1.8`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `0.1.8` release.
Here you can find all related translations changes: [0.1.7...master](https://github.com/flarum-lang/hindi/compare/0.1.7...master).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## 0.1.8

**सामान्य अद्यतन**:

* Flarum सत्यापन अनुवाद अपडेट किये गए हैं.

**नए एक्सटेंशन के लिए समर्थन जोड़ा गया है**:

* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/nicknames`](https://github.com/flarum/nicknames)
* [`flarum/pusher`](https://github.com/flarum/pusher)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`flarum/sticky`](https://github.com/flarum/sticky)
* [`flarum/subscriptions`](https://github.com/flarum/subscriptions)
* [`fof/upload`](https://github.com/FriendsOfFlarum/upload)

सभी परिवर्तन: [0.1.7...0.1.8](https://github.com/flarum-lang/hindi/compare/0.1.7...0.1.8)।

</details>

### CODE REVIEW

**Comment by ItsNeil17** [comment]
Ok cool, gonna do alot of changes starting this friday

**Comment by ItsNeil17** [comment]
Doing some final translations & releasing today!

**Comment by ItsNeil17** [comment]
okay yeah no I didn't abandon this ahh

**Review by ItsNeil17 — APPROVED** [review]
lgtm

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## संस्करण [`0.1.8`](https://github.com/flarum-lang/hindi/releases/tag/0.1.8)

**सामान्य अद्यतन**:

* Flarum सत्यापन अनुवाद अपडेट किये गए हैं.


**नए एक्सटेंशन के लिए समर्थन जोड़ा गया है**:

* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/nicknames`](https://github.com/flarum/nicknames)
* [`flarum/pusher`](https://github.com/flarum/pusher)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`flarum/sticky`](https://github.com/flarum/sticky)
* [`flarum/subscriptions`](https://github.com/flarum/subscriptions)
* [`fof/upload`](https://github.com/FriendsOfFlarum/upload)


सभी परिवर्तन: [0.1.7...0.1.8](https://github.com/flarum-lang/hindi/compare/0.1.7...0.1.8)।

अपडेट करने के लिए इन आदेशों को चलाएँ:

```console
composer update flarum-lang/hindi
php flarum cache:clear
```

~~~

**Pull request merged**
